version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15.6-buster
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Run build
          command: go build hello.go
      - run:
          name: Archive files
          command: tar cJf hello.tar.xz hello
      - store_artifacts:
          path: hello.tar.xz
  setup:
    executor: default
    steps:
      - run:
          name: Update apt cache
          command: sudo apt update
      - run:
          name: Install dependencies
          command: |
            sudo apt install build-essential ruby ruby-bundler
      - checkout
  message:
    executor: default
    steps:
      - setup_remote_docker
      - run:
          name: "Show message"
          command: docker run --interactive --rm --tty --name alpine alpine:edge echo 'Fight dayo!'
workflows:
  version: 2
  test:
    jobs:
      - setup
      - message:
          requires:
            - setup
      - build:
          requires:
            - message
