version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15.6-buster
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Run build
          command: go build hello.go
      - store_artifacts:
          path: hello
          destination: ./artifacts
      - persist_to_workspace:
          root: .
          paths:
            - hello
  release:
    executor: default
    steps:
      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Release"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete 0.0.1 ./artifacts/
  setup:
    executor: default
    steps:
      - run:
          name: Update apt cache
          command: sudo apt update
      - run:
          name: Install dependencies
          command: |
            sudo apt install build-essential ruby ruby-bundler
      - checkout
  message:
    executor: default
    steps:
      - setup_remote_docker
      - run:
          name: "Show message"
          command: docker run --interactive --rm --tty --name alpine alpine:edge echo 'Fight dayo!'
workflows:
  version: 2
  test:
    jobs:
      - setup
      - message:
          requires:
            - setup
      - build:
          requires:
            - message
      - release:
          requires:
            - build
