version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15.6-buster
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build hello
          command: ./scripts/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - *
  release:
    executor: default
    steps:
      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Release"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete 0.0.1 ./artifacts/
workflows:
  version: 2
  release:
    jobs:
      - build
      - release:
          requires:
            - build
