version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15.6-buster
    working_directory: ~/hello
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build hello
          command: make release
      - persist_to_workspace:
          root: ./build
          paths:
            - ./release/*
  e2e:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup
          command: |
            sudo apt install --yes ruby-bundler
      - run:
          name: Run e2e tests
          command: echo "e2e test ... OK"
  lint:
    executor: default
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo apt install --yes ruby-bundler
            make install
      - run:
          name: Run lint
          command: echo "lint ... OK"
  publish:
    executor: default
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Setup
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Prepare
          command: |
            cd ./artfacts/build/release
            zip -9 -r ./artifacts/release/hello.zip hello
      - run:
          name: Release hello
          command: |
            VERSION=$(./artifacts/build/release/hello/linux-amd64/bin/hello --version | tr -d "\r\n")
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -delete ${VERSION} ./artifacts/release/hello.zip
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: echo "Test ... OK"

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
      - e2e
      - build:
          filters:
            branches:
              only: master
          requires:
            - lint
            - test
            - e2e
      - publish:
          filters:
            branches:
              only: master
          requires:
            - build
