version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15.6-buster
jobs:
  setup:
    executor: default
    steps:
      - run:
          name: Update apt cache
          command: sudo apt update
      - run:
          name: Install dependencies
          command: |
            sudo apt install build-essential ruby ruby-bundler
  message:
    executor: default
    steps:
      - run:
          name: "Show message"
          command: docker run --interactive --rm --tty --name alpine alpine:edge echo 'Fight dayo!'
workflows:
  version: 2
  test:
    jobs:
      - setup
      - message
