version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15.6-buster
    working_directory: ~/hello
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build hello
          command: ./scripts/build.sh
      - persist_to_workspace:
          root: build
          paths:
            - release/*
  release:
    executor: default
    steps:
      - attach_workspace:
            at: ./artifacts
      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Prepare
          command: |
            cd ./artifacts/release
            zip -9 -r hello.zip ./hello
      - run:
          name: Publish
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete 0.0.1 ./artifacts/release/hello.zip
workflows:
  version: 2
  release:
    jobs:
      - build
      - release:
          requires:
            - build
