version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.15.6-buster
    working_directory: ~/hello

jobs:
  tests:
    executor: default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup
          command: |
            sudo apt install --yes ruby-bundler
            make install
      - run:
          name: Run tests
          command: |
            make lint
            make test
            make e2e
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build hello
          command: make release
      - persist_to_workspace:
          root: ./build
          paths:
            - ./release/*
  publish:
    executor: default
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Setup
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Prepare
          command: |
            cd ./artifacts/release
            zip -9 -r ./hello.zip hello
      - run:
          name: Release hello
          command: |
            VERSION=$(./artifacts/release/hello/linux-amd64/bin/hello --version | cut -d " " -f 3 | tr -d "\r\n")
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -delete ${VERSION} ./artifacts/release/hello.zip

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            filters:
              tags:
                only: /.*/
      - build:
          filters:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v[0-9](\.[0-9]+){2}$/
          requires:
            - tests
      - publish:
          filters:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v[0-9](\.[0-9]+){2}$/
          requires:
            - build
