version: 2.1
executors:
    default:
        docker:
            -   image: circleci/golang:1.15.6-buster
jobs:
    setup:
        executor: default
        steps:
            - run:
                  name: Update cache
                  command: apt update
            - run:
                  name: Install dependencies
                  command: sudo apt install build-essential ruby ruby-bundler
    hello:
        executor: default
        steps:
            -   run:
                    name: "Say hello"
                    command: |
                        sudo docker run --interactive --rm --tty \
                            --name alpine alpine:edge \
                            echo 'Fight dayo!'"
workflows:
    version: 2
    hello:
        jobs:
            - setup
            - hello
